# PRODUCTION ANALYSIS
The objective of this notebook is to analyse the contribution companies to box office success. By examining total revenue, average revenue, and movie production counts, this analysis aims to identify the companies that have consistently produced commercially successful films.

# Research Question

Which production companies have produced the highest-grossing movies?

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

## TOP PRODUCTION COMPANIES BY TOTAL REVENUE

In [ ]:
# TOP PRODDUCTION COMPANIES BY TOTAL REVENUE

query = """
SELECT
    company,
    ROUND(SUM(gross), 2) AS Total_Revenue
FROM movies
WHERE company IS NOT NULL
GROUP BY company
ORDER BY Total_Revenue DESC
LIMIT 20;
"""

top_revenue_companies = pd.read_sql(query, connection)

top_revenue_companies

                          company  Total_Revenue
0                    Warner Bros.   5.649142e+10
1              Universal Pictures   5.251419e+10
2               Columbia Pictures   4.300894e+10
3              Paramount Pictures   4.049361e+10
4           Twentieth Century Fox   4.025705e+10
5            Walt Disney Pictures   3.632789e+10
6                 New Line Cinema   1.988380e+10
7                  Marvel Studios   1.506559e+10
8            DreamWorks Animation   1.187361e+10
9             Touchstone Pictures   1.179583e+10
10            Dreamworks Pictures   1.163544e+10
11      Metro-Goldwyn-Mayer (MGM)   9.230230e+09
12           Summit Entertainment   8.373719e+09
13        Pixar Animation Studios   7.886345e+09
14              Fox 2000 Pictures   7.443503e+09
15                      Lucasfilm   7.185352e+09
16  Walt Disney Animation Studios   6.751509e+09
17                      Lionsgate   6.078453e+09
18               TriStar Pictures   5.667436e+09
19                    Screen Gems   4.113025e+09

## TOP PRODUCTION COMPANIES BY NUMBER OF MOVIES

In [ ]:
# TOP PRODUCTION COMPANIES BY NUMBER OF MOVIES

query = """
SELECT
    company,
    COUNT(*) AS Number_of_Movies
FROM movies
WHERE company IS NOT NULL
GROUP BY company
ORDER BY Number_of_Movies DESC
LIMIT 20;
"""

movie_count = pd.read_sql(query, connection)

movie_count

                      company  Number_of_Movies
0          Universal Pictures               377
1                Warner Bros.               334
2           Columbia Pictures               332
3          Paramount Pictures               320
4       Twentieth Century Fox               240
5             New Line Cinema               174
6         Touchstone Pictures               132
7   Metro-Goldwyn-Mayer (MGM)               125
8        Walt Disney Pictures               123
9            TriStar Pictures                94
10        Dreamworks Pictures                76
11                    Miramax                74
12          Fox 2000 Pictures                63
13       Summit Entertainment                60
14             Orion Pictures                60
15  Castle Rock Entertainment                59
16                  Lionsgate                58
17   Fox Searchlight Pictures                57
18                Screen Gems                56
19            Dimension Films                56

# Summary

The analysis demonstrates that production companies differ considerably in both their output and financial performance. Some companies generate high revenue through a large number of movie releases, while others achieve exceptional average revenue despite producing fewer films. Analysing profit alongside revenue provides a more complete measure of commercial success by accounting for production costs. These findings suggest that production company is an important factor associated with box office success.