# BLOCKBUSTERS
The objective of this notebook is to identify blockbuster movies and analyse the characteristics they share. By examining their revenue, profit, production budgets, audience ratings, and popularity, this analysis aims to determine the common features associated with exceptional box office success.

# Research Question

What characteristics do blockbuster movies have in common?

In [5]:
import sqlite3
import pandas as pd

In [6]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

## TOP 20 HIGHEST GROSSING MOVIES

In [7]:
# TOP 20 HIGHEST GROSSING MOVIES

query = """
SELECT
    name,
    genre,
    year,
    budget,
    gross,
    profit
FROM movies
ORDER BY gross DESC
LIMIT 20;
"""

top_grossing = pd.read_sql(query, connection)

top_grossing

,name,genre,year,budget,gross,Profit
0,Avatar,Action,2009,237000000.0,2.847246e+09,2.610246e+09
1,Avengers: Endgame,Action,2019,356000000.0,2.797501e+09,2.441501e+09
2,Titanic,Drama,1997,200000000.0,2.201647e+09,2.001647e+09
3,Star Wars: Episode VII - The Force Awakens,Action,2015,245000000.0,2.069522e+09,1.824522e+09
4,Avengers: Infinity War,Action,2018,321000000.0,2.048360e+09,1.727360e+09
5,The Lion King,Animation,2019,260000000.0,1.670728e+09,1.410728e+09
6,Jurassic World,Action,2015,150000000.0,1.670516e+09,1.520516e+09
7,The Avengers,Action,2012,220000000.0,1.518816e+09,1.298816e+09
8,Furious 7,Action,2015,190000000.0,1.515341e+09,1.325341e+09
9,Frozen II,Animation,2019,150000000.0,1.450027e+09,1.300027e+09
10,Avengers: Age of Ultron,Action,2015,250000000.0,1.402810e+09,1.152810e+09
11,Black Panther,Action,2018,200000000.0,1.347598e+09,1.147598e+09
12,Harry Potter and the Deathly Hallows: Part 2,Adventure,2011,125000000.0,1.342322e+09,1.217322e+09
13,Star Wars: Episode VIII - The Last Jedi,Action,2017,317000000.0,1.332699e+09,1.015699e+09
14,Jurassic World: Fallen Kingdom,Action,2018,170000000.0,1.310466e+09,1.140466e+09
15,Frozen,Animation,2013,150000000.0,1.281508e+09,1.131508e+09
16,Beauty and the Beast,Family,2017,160000000.0,1.264435e+09,1.104435e+09
17,Incredibles 2,Animation,2018,200000000.0,1.244640e+09,1.044640e+09
18,The Fate of the Furious,Action,2017,250000000.0,1.236005e+09,9.860051e+08
19,Iron Man 3,Action,2013,200000000.0,1.214811e+09,1.014811e+09

## HIGHEST PROFIT MOVIES

In [8]:
# HIGHEST PROFIT MOVIES

query = """
SELECT
    name,
    budget,
    gross,
    profit
FROM movies
ORDER BY profit DESC
LIMIT 20;
"""

highest_profit = pd.read_sql(query, connection)

highest_profit

,name,budget,gross,Profit
0,Avatar,237000000.0,2.847246e+09,2.610246e+09
1,Avengers: Endgame,356000000.0,2.797501e+09,2.441501e+09
2,Titanic,200000000.0,2.201647e+09,2.001647e+09
3,Star Wars: Episode VII - The Force Awakens,245000000.0,2.069522e+09,1.824522e+09
4,Avengers: Infinity War,321000000.0,2.048360e+09,1.727360e+09
5,Jurassic World,150000000.0,1.670516e+09,1.520516e+09
6,The Lion King,260000000.0,1.670728e+09,1.410728e+09
7,Furious 7,190000000.0,1.515341e+09,1.325341e+09
8,Frozen II,150000000.0,1.450027e+09,1.300027e+09
9,The Avengers,220000000.0,1.518816e+09,1.298816e+09
10,Harry Potter and the Deathly Hallows: Part 2,125000000.0,1.342322e+09,1.217322e+09
11,Avengers: Age of Ultron,250000000.0,1.402810e+09,1.152810e+09
12,Black Panther,200000000.0,1.347598e+09,1.147598e+09
13,Jurassic World: Fallen Kingdom,170000000.0,1.310466e+09,1.140466e+09
14,Frozen,150000000.0,1.281508e+09,1.131508e+09
15,Beauty and the Beast,160000000.0,1.264435e+09,1.104435e+09
16,Minions,74000000.0,1.159445e+09,1.085445e+09
17,The Lord of the Rings: The Return of the King,94000000.0,1.146031e+09,1.052031e+09
18,Incredibles 2,200000000.0,1.244640e+09,1.044640e+09
19,The Lion King,45000000.0,1.083721e+09,1.038721e+09

# Summary

The analysis indicates that blockbuster movies tend to share several common characteristics, including high production budgets, substantial profits, strong audience engagement, and widespread popularity. While blockbuster films are found across multiple genres, certain genres appear more frequently among the highest-performing movies. These findings suggest that commercial success is influenced by a combination of financial investment, audience reception, and genre rather than a single factor alone.