# RETURN ON INVESTMENT ANALYSIS
The objective of this notebook is to evaluate the financial efficiency of movies by analysing their Return on Investment (ROI). Unlike revenue or profit alone, ROI measures how effectively a movie converted its production budget into financial returns, providing insight into which movies delivered the greatest value for their investment.

# Research Question
Which movies generated the highest return relative to their production budgets?

In [5]:
import sqlite3
import pandas as pd

In [6]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

## HIGHEST ROI MOVIES

In [7]:
# HIGHEST ROI MOVIES

query = """
SELECT
    name,
    budget,
    gross,
    ROI
FROM movies
WHERE ROI IS NOT NULL
ORDER BY ROI DESC
LIMIT 20;
"""

highest_roi = pd.read_sql(query, connection)

highest_roi

                          name      budget        gross           ROI
0          Paranormal Activity     15000.0  193355800.0  12889.386667
1      The Blair Witch Project     60000.0  248639099.0   4142.984983
2                  The Gallows    100000.0   42964410.0    428.644100
3                  El Mariachi      7000.0    2040920.0    290.560000
4                         Once    150000.0   20936722.0    138.578147
5                       Clerks     27000.0    3151130.0    115.708519
6            Napoleon Dynamite    400000.0   46138887.0    114.347217
7        In the Company of Men     25000.0    2804473.0    111.178920
8                  Keeping Mum    169000.0   18586834.0    108.981266
9                   Open Water    500000.0   54683487.0    108.366974
10            The Devil Inside   1000000.0  101758490.0    100.758490
11              The Quiet Ones    200000.0   17835162.0     88.175810
12                         Saw   1200000.0  103911669.0     85.593058
13                   Searching    880000.0   75462037.0     84.752315
14                      Primer      7000.0     545436.0     76.919429
15  E.T. the Extra-Terrestrial  10500000.0  792910554.0     74.515291
16    My Big Fat Greek Wedding   5000000.0  368744044.0     72.748809
17              The Full Monty   3500000.0  257938649.0     72.696757
18             Friday the 13th    550000.0   39754601.0     71.281093
19                   Fireproof    500000.0   33473297.0     65.946594

## LOWEST ROI MOVIES

In [8]:
# LOWEST ROI MOVIES

query = """
SELECT
    name,
    budget,
    gross,
    ROI
FROM movies
WHERE ROI IS NOT NULL
ORDER BY ROI ASC
LIMIT 20;
"""

lowest_roi = pd.read_sql(query, connection)

lowest_roi

                          name      budget    gross       ROI
0                   Trojan War  15000000.0    309.0 -0.999979
1                     Madadayo  11900000.0    596.0 -0.999950
2                 Ginger Snaps   5000000.0   2554.0 -0.999489
3   Philadelphia Experiment II   5000000.0   2970.0 -0.999406
4     The Lovers on the Bridge  28000000.0  29679.0 -0.998940
5                       Savior  10000000.0  14328.0 -0.998567
6                  Tanner Hall   3000000.0   5073.0 -0.998309
7                    Crimewave   3000000.0   5101.0 -0.998300
8                     Deadfall  10000000.0  18369.0 -0.998163
9               Hell's Kitchen   6000000.0  11710.0 -0.998048
10                    Barefoot   6000000.0  15071.0 -0.997488
11                     Freaked  11000000.0  29296.0 -0.997337
12                    Parasite    800000.0   2270.0 -0.997162
13                Passion Play   8000000.0  25603.0 -0.996800
14                About Cherry   2500000.0   8315.0 -0.996674
15                 Rock & Rule   8000000.0  30379.0 -0.996203
16             Best Laid Plans   7000000.0  27816.0 -0.996026
17                Brenda Starr  16000000.0  67878.0 -0.995758
18             O.C. and Stiggs   7000000.0  29815.0 -0.995741
19             My Summer Story  15000000.0  70936.0 -0.995271

# Summary

The ROI analysis demonstrates that financial efficiency is an important dimension of box office success. While some blockbuster movies generated exceptional profits through large budgets, other films achieved remarkable returns with relatively modest investments. Evaluating ROI alongside revenue and profit provides a more comprehensive understanding of commercial performance and highlights that successful movies are not necessarily those with the highest budgets, but those that maximise returns on investment.