# Budget vs. Revenue
The objective of this notebooks is to navigate the relationship a movie's production budget and its box office revenue using SQL queries. By comparing production costs with gross earnings, this analysis aims to determine whether higher budget movies generally achieve greater commercial success and to identify movies that generated exceptional high profits.

# Research Question
Is there a relationship between a movie's production budget and its box office revenue?

In [2]:
import sqlite3
import pandas as pd

In [3]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

## TOP 20 HIGHEST BUDGET MOVIES

In [4]:
# TOP 20 HIGHEST BUDGET MOVIES
query = """
SELECT
    name,
    budget,
    gross
FROM movies
ORDER BY budget DESC
LIMIT 20;
"""

highest_budget = pd.read_sql(query, connection)

highest_budget

                                             name       budget         gross
0                               Avengers: Endgame  356000000.0  2.797501e+09
1                          Avengers: Infinity War  321000000.0  2.048360e+09
2         Star Wars: Episode VIII - The Last Jedi  317000000.0  1.332699e+09
3        Pirates of the Caribbean: at World's End  300000000.0  9.609965e+08
4                                  Justice League  300000000.0  6.579270e+08
5                         Solo: A Star Wars Story  275000000.0  3.929248e+08
6   Star Wars: Episode IX - The Rise of Skywalker  275000000.0  1.078233e+09
7                                Superman Returns  270000000.0  3.910812e+08
8                                         Tangled  260000000.0  5.924628e+08
9                                   The Lion King  260000000.0  1.670728e+09
10                                   Spider-Man 3  258000000.0  8.949834e+08
11         Harry Potter and the Half-Blood Prince  250000000.0  9.344541e+08
12    Pirates of the Caribbean: on Stranger Tides  250000000.0  1.045714e+09
13                          The Dark Knight Rises  250000000.0  1.081143e+09
14                                    John Carter  250000000.0  2.841391e+08
15      The Hobbit: The Battle of the Five Armies  250000000.0  9.621829e+08
16                        Avengers: Age of Ultron  250000000.0  1.402810e+09
17                     Captain America: Civil War  250000000.0  1.153337e+09
18             Batman v Superman: Dawn of Justice  250000000.0  8.736375e+08
19                        The Fate of the Furious  250000000.0  1.236005e+09

## TOP 20 HIGHEST GROSSING MOVIES

In [5]:
# TOP 20 HIGHEST GROSSING MOVIES

query = """
SELECT
    name,
    budget,
    gross
FROM movies
ORDER BY gross DESC
LIMIT 20;
"""

highest_gross = pd.read_sql(query, connection)

highest_gross

                                            name       budget         gross
0                                         Avatar  237000000.0  2.847246e+09
1                              Avengers: Endgame  356000000.0  2.797501e+09
2                                        Titanic  200000000.0  2.201647e+09
3     Star Wars: Episode VII - The Force Awakens  245000000.0  2.069522e+09
4                         Avengers: Infinity War  321000000.0  2.048360e+09
5                                  The Lion King  260000000.0  1.670728e+09
6                                 Jurassic World  150000000.0  1.670516e+09
7                                   The Avengers  220000000.0  1.518816e+09
8                                      Furious 7  190000000.0  1.515341e+09
9                                      Frozen II  150000000.0  1.450027e+09
10                       Avengers: Age of Ultron  250000000.0  1.402810e+09
11                                 Black Panther  200000000.0  1.347598e+09
12  Harry Potter and the Deathly Hallows: Part 2  125000000.0  1.342322e+09
13       Star Wars: Episode VIII - The Last Jedi  317000000.0  1.332699e+09
14                Jurassic World: Fallen Kingdom  170000000.0  1.310466e+09
15                                        Frozen  150000000.0  1.281508e+09
16                          Beauty and the Beast  160000000.0  1.264435e+09
17                                 Incredibles 2  200000000.0  1.244640e+09
18                       The Fate of the Furious  250000000.0  1.236005e+09
19                                    Iron Man 3  200000000.0  1.214811e+09

## TOP 20 MOST PROFITABLE MOVIES

In [6]:
# TOP 20 MOST PROFITABLE MOVIES

query = """
SELECT
    name,
    budget,
    gross,
    profit
FROM movies
ORDER BY profit DESC
LIMIT 20;
"""

highest_profit = pd.read_sql(query, connection)

highest_profit

,name,budget,gross,Profit
0,Avatar,237000000.0,2.847246e+09,2.610246e+09
1,Avengers: Endgame,356000000.0,2.797501e+09,2.441501e+09
2,Titanic,200000000.0,2.201647e+09,2.001647e+09
3,Star Wars: Episode VII - The Force Awakens,245000000.0,2.069522e+09,1.824522e+09
4,Avengers: Infinity War,321000000.0,2.048360e+09,1.727360e+09
5,Jurassic World,150000000.0,1.670516e+09,1.520516e+09
6,The Lion King,260000000.0,1.670728e+09,1.410728e+09
7,Furious 7,190000000.0,1.515341e+09,1.325341e+09
8,Frozen II,150000000.0,1.450027e+09,1.300027e+09
9,The Avengers,220000000.0,1.518816e+09,1.298816e+09
10,Harry Potter and the Deathly Hallows: Part 2,125000000.0,1.342322e+09,1.217322e+09
11,Avengers: Age of Ultron,250000000.0,1.402810e+09,1.152810e+09
12,Black Panther,200000000.0,1.347598e+09,1.147598e+09
13,Jurassic World: Fallen Kingdom,170000000.0,1.310466e+09,1.140466e+09
14,Frozen,150000000.0,1.281508e+09,1.131508e+09
15,Beauty and the Beast,160000000.0,1.264435e+09,1.104435e+09
16,Minions,74000000.0,1.159445e+09,1.085445e+09
17,The Lord of the Rings: The Return of the King,94000000.0,1.146031e+09,1.052031e+09
18,Incredibles 2,200000000.0,1.244640e+09,1.044640e+09
19,The Lion King,45000000.0,1.083721e+09,1.038721e+09

## HIGHEST MOVIES THAT LOST MONEY

In [7]:
# HIGHEST BUDGET MOVIES THAT LOST MONEY

query = """
SELECT
    name,
    budget,
    gross,
    profit
FROM movies
WHERE profit < 0
ORDER BY budget DESC
LIMIT 20;
"""

losses = pd.read_sql(query, connection)

losses

                                 name       budget        gross       Profit
0                       Evan Almighty  175000000.0  174440724.0    -559276.0
1                            47 Ronin  175000000.0  151783839.0  -23216161.0
2    King Arthur: Legend of the Sword  175000000.0  148675066.0  -26324934.0
3                    The 13th Warrior  160000000.0   61698899.0  -98301101.0
4                        The Irishman  159000000.0     968853.0 -158031147.0
5                                 Pan  150000000.0  128388320.0  -21611680.0
6                     Treasure Planet  140000000.0  110041363.0  -29958637.0
7   Final Fantasy: The Spirits Within  137000000.0   85131830.0  -51868170.0
8                             Stealth  135000000.0   79268322.0  -55731678.0
9                The Call of the Wild  135000000.0  111105497.0  -23894503.0
10                             Sahara  130000000.0  119240351.0  -10759649.0
11                           R.I.P.D.  130000000.0   78324220.0  -51675780.0
12                     Monster Trucks  125000000.0   64493915.0  -60506085.0
13                        Speed Racer  120000000.0   93945766.0  -26054234.0
14                    How Do You Know  120000000.0   48668907.0  -71331093.0
15                        Windtalkers  115000000.0   77628265.0  -37371735.0
16            xXx: State of the Union  113000000.0   71022693.0  -41977307.0
17        Around the World in 80 Days  110000000.0   72178895.0  -37821105.0
18                  The Good Shepherd  110000000.0  100266865.0   -9733135.0
19                      Live by Night  108000000.0   22678555.0  -85321445.0

## AVERAGE BUDGET VS. BUDGET REVENUE

In [8]:
# AVERAGE BUDGET VS. BUDGET REVENUE

query = """
SELECT
    ROUND(AVG(budget),2) AS Average_Budget,
    ROUND(AVG(gross),2) AS Average_Revenue,
    ROUND(AVG(profit),2) AS Average_Profit
FROM movies;
"""

summary = pd.read_sql(query, connection)

summary

   Average_Budget  Average_Revenue  Average_Profit
0     35589876.19      78500541.02      67065820.5

# Summary

The SQL analysis suggests that production budget plays an important role in determining box office performance, as many of the highest-grossing movies also have substantial production budgets. However, the presence of high-budget movies that generated financial losses indicates that budget alone is not sufficient to guarantee commercial success. Other factors, such as genre, popularity, audience reception, and production company, may also contribute significantly to financial performance and will be investigated in the following notebooks.

In [9]:
connection.close()

print("Database connection closed.")

Database connection closed.