# GENRE ANALYSIS
The objective of this notebook is to analyse the financial performance of different movie genres using SQL queries. By comparing average and total box office revenue across genres, this analysis aims to identify which genres have historically achieved the greatest commercial success and determine whether genre is associated with box office performance.

# Research Question

Which movie genres generate the highest average box office revenue?

In [1]:
import sqlite3
import pandas as pd

In [2]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

## HIGHEST AVERAGE BY GENRE

In [ ]:
# Highest Average by Genre

query = """
SELECT
    genre,
    ROUND(AVG(gross), 2) AS Average_Revenue
FROM movies
GROUP BY genre
ORDER BY Average_Revenue DESC;
"""

average_genre = pd.read_sql(query, connection)

average_genre

        genre  Average_Revenue
0   Animation     2.392300e+08
1      Family     1.961725e+08
2      Action     1.455086e+08
3   Adventure     1.093252e+08
4     Mystery     1.011835e+08
5   Biography     4.787432e+07
6      Horror     4.737241e+07
7      Comedy     4.433187e+07
8       Crime     3.940120e+07
9       Drama     3.893096e+07
10    Fantasy     3.870933e+07
11     Sci-Fi     3.256123e+07
12   Thriller     2.693526e+07
13    Romance     2.354937e+07
14    Western     1.067530e+07
15    Musical     2.595346e+06
16      Sport     1.067629e+06
17      Music     1.100140e+05
18    History              NaN

## HIGHEST TOTAL REVENUE BY GENRE

In [4]:
# Highest Total Revenue by Genre

query = """
SELECT
    genre,
    ROUND(SUM(gross), 2) AS Total_Revenue
FROM movies
GROUP BY genre
ORDER BY Total_Revenue DESC;
"""

total_genre = pd.read_sql(query, connection)

total_genre

        genre  Total_Revenue
0      Action   2.434359e+11
1      Comedy   9.717547e+10
2   Animation   8.014205e+10
3       Drama   5.715065e+10
4   Adventure   4.591660e+10
5       Crime   2.135545e+10
6   Biography   2.072958e+10
7      Horror   1.454333e+10
8      Family   2.157897e+09
9     Mystery   2.023671e+09
10    Fantasy   1.664501e+09
11   Thriller   3.232231e+08
12     Sci-Fi   2.604899e+08
13    Romance   1.883950e+08
14    Western   3.202589e+07
15    Musical   5.190692e+06
16      Sport   1.067629e+06
17      Music   1.100140e+05
18    History            NaN

# Summary

The SQL analysis indicates that movie genre is associated with financial performance. Some genres consistently generate higher average and total box office revenue than others, suggesting that audience preferences differ across genres. However, genre performance should also be interpreted alongside production frequency, as genres with more movie releases may naturally accumulate greater total revenue. These findings provide evidence that genre is an important factor to consider when analysing box office success.

In [ ]:
connection.close()

print("Database connection closed.")