# CORRELATION ANALYSIS
The objective of this notebook is to statistically validate the relationships identified during Exploratory Data Analysis (EDA). Pearson's correlation coefficient is used to measure the strength and direction of linear relationships between key numerical variables in the movie dataset. These results provide quantitive evidence to support or challenge the visual patterns observed in previous analyses. 

# Research Questions
- Is there a relationship between a movie's production budget and its box office revenue?
- Is popularity associated with financial success?
- Which movies generated the highest return on investment (ROI)?

In [36]:
import pandas as pd
from scipy.stats import pearsonr

In [37]:
clean = (
    r"C:\Users\bongo\OneDrive\Desktop\GitHub"
    r"\Movie Analysis\Data\Clean\cleaned_movies.csv"
)

movies = pd.read_csv(clean)

print("Dataset loaded successfully.")

movies.head()

Dataset loaded successfully.

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
0,The Shining,R,Drama,1980,1980-06-13,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,1.473620,1980-06-13,2.0,1980
1,The Blue Lagoon,R,Adventure,1980,1980-07-02,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,12.078468,1980-07-02,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,1980-06-20,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,28.909726,1980-06-20,2.0,1980
3,Airplane!,PG,Comedy,1980,1980-07-02,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,22.843868,1980-07-02,3.0,1980
4,Caddyshack,R,Comedy,1980,1980-07-25,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,5.641057,1980-07-25,3.0,1980

In [38]:
print(f"Rows: {movies.shape[0]:,}")
print(f"Columns: {movies.shape[1]}")

movies.info()

Rows: 7,668
Columns: 20
<class 'pandas.DataFrame'>
RangeIndex: 7668 entries, 0 to 7667
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             7668 non-null   str
 1   rating           7591 non-null   str
 2   genre            7668 non-null   str
 3   year             7668 non-null   int64
 4   released         7609 non-null   str
 5   score            7665 non-null   float64
 6   votes            7665 non-null   float64
 7   director         7668 non-null   str
 8   writer           7665 non-null   str
 9   star             7667 non-null   str
 10  country          7665 non-null   str
 11  budget           5497 non-null   float64
 12  gross            7479 non-null   float64
 13  company          7651 non-null   str
 14  runtime          7664 non-null   float64
 15  Profit           5436 non-null   float64
 16  ROI              5436 non-null   float64
 17  released_month   7609 non-null   str
 18  release_quarter  7609 non-null   float64
 19  decade           7668 non-null   int64
dtypes: float64(8), int64(2), str(10)
memory usage: 1.2 MB

In [39]:
def correlation_analysis(data, x, y):
    """
    Calculate and display the Pearson correlation coefficient and p-value for two numerical variables
    """
    correlation, p_value = pearsonr(data[x], data[y])

    print(f'\n{x} vs {y}')
    print(f'Correlation: {correlation:.3f}')
    print(f'P-value: {p_value:.6f}')

    return correlation, p_value

## Budget vs. Gross

In [40]:
correlation_analysis(movies, 'budget', 'gross')

budget vs gross
Correlation: nan
P-value: nan

(np.float64(nan), np.float64(nan))

### Correlation: 0.74
Production budget demonstrated a Strong Positive correlation (r = 0.74) with box office revenue, indication that higher-budget productions generally generate greater financial returns. However, because the relationship is not perfect, production budget alone is insuficient to explain commercial success, suggesting that additional factors also influence revenue generation.

## Gross vs. Votes

In [41]:
correlation_analysis(movies, 'gross', 'votes')

gross vs votes
Correlation: nan
P-value: nan

(np.float64(nan), np.float64(nan))

### Correlation: 0.631
Audience vote count demonstrates a moderately Strong Positive relationship (r=0.631) with box office revenue. Movies attracting greater audience participation generally achieved higher commercial performance, suggesting that public engagement is more closely associated with financial success than critic ratings alone.

## Gross vs. IMDb Score

In [42]:
correlation_analysis(movies, 'gross', 'score')

gross vs score
Correlation: nan
P-value: nan

(np.float64(nan), np.float64(nan))

### Correlation: 0.186
IMDb ratings show only a Very Weak Positive relationship (r=0.186) with box office revenue. While critically well received films may achieve commercial success, audience ratings alone are poor predictors of financial performance.

## Budget vs. ROI

In [43]:
correlation_analysis(movies, 'budget', 'ROI')

budget vs ROI
Correlation: nan
P-value: nan

(np.float64(nan), np.float64(nan))

### Correlation: -0.018
Production budget shows virtually no relationship with return on investment (r= -0.018). This suggests that increasing production expenditure does not necessarily improve investment efficiency. Smaller budget films are capable of generating returns comparable to, or exceeding, those of major blockbuster productions.

## Profit vs. Gross

In [44]:
correlation_analysis(movies, 'Profit', 'gross')

Profit vs gross
Correlation: nan
P-value: nan

(np.float64(nan), np.float64(nan))

### Correlation: 0.984
Gross revenue demonstrates an extremely Strong Positive relationship with profit (r= 0.984). This result is expected because profit is directly derived from box office revenue after accounting for production budget. Consequently, revenue is the strongest predictor of overall profitability within the dataset.

## Correlation Matrix

In [45]:
columns = [
    'budget',
    'gross',
    'Profit',
    'ROI',
    'votes',
    'score'
]

movies[columns].corr(method='pearson')

          budget     gross    Profit       ROI     votes     score
budget  1.000000  0.740395  0.610661 -0.018133  0.442429  0.076254
gross   0.740395  1.000000  0.984418  0.016303  0.630757  0.186258
Profit  0.610661  0.984418  1.000000  0.023951  0.609313  0.242928
ROI    -0.018133  0.016303  0.023951  1.000000  0.017543  0.004083
votes   0.442429  0.630757  0.609313  0.017543  1.000000  0.409182
score   0.076254  0.186258  0.242928  0.004083  0.409182  1.000000