# DESCRIPTIVE STATISTICS
The objective of this notebook is to generate descriptive statistical summaries of the movie dataset. These statistics complement the exploratory data analysis by describing the central tendency, variability, distribution and shape of key numerical qualities of movies while helping identify skewed distributions, variability and potential outliers.

## Research Questions
- Budget vs. Revenue
- Genres and Revenue
- Popularity and Financial Success
- Characteristics of Blockbusters
- ROI

In [18]:
import pandas as pd

In [19]:
clean = (
    r"C:\Users\bongo\OneDrive\Desktop\GitHub"
    r"\Movie Analysis\Data\Clean\cleaned_movies.csv"
)

movies = pd.read_csv(clean)

print("Dataset loaded successfully.")

movies.head()

Dataset loaded successfully.

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
0,The Shining,R,Drama,1980,1980-06-13,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,1.473620,1980-06-13,2.0,1980
1,The Blue Lagoon,R,Adventure,1980,1980-07-02,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,12.078468,1980-07-02,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,1980-06-20,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,28.909726,1980-06-20,2.0,1980
3,Airplane!,PG,Comedy,1980,1980-07-02,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,22.843868,1980-07-02,3.0,1980
4,Caddyshack,R,Comedy,1980,1980-07-25,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,5.641057,1980-07-25,3.0,1980

In [20]:
print(f"Rows: {movies.shape[0]:,}")
print(f"Columns: {movies.shape[1]}")

movies.info()

Rows: 7,668
Columns: 20
<class 'pandas.DataFrame'>
RangeIndex: 7668 entries, 0 to 7667
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             7668 non-null   str
 1   rating           7591 non-null   str
 2   genre            7668 non-null   str
 3   year             7668 non-null   int64
 4   released         7609 non-null   str
 5   score            7665 non-null   float64
 6   votes            7665 non-null   float64
 7   director         7668 non-null   str
 8   writer           7665 non-null   str
 9   star             7667 non-null   str
 10  country          7665 non-null   str
 11  budget           5497 non-null   float64
 12  gross            7479 non-null   float64
 13  company          7651 non-null   str
 14  runtime          7664 non-null   float64
 15  Profit           5436 non-null   float64
 16  ROI              5436 non-null   float64
 17  released_month   7609 non-null   str
 18  release_quarter  7609 non-null   float64
 19  decade           7668 non-null   int64
dtypes: float64(8), int64(2), str(10)
memory usage: 1.2 MB

In [21]:
numerical_columns = [
    'budget',
    'gross',
    'Profit',
    'ROI',
    'votes',
    'score',
    'runtime',
    'year'
]

numerical_data = movies[numerical_columns]
numerical_data.head()

,budget,gross,Profit,ROI,votes,score,runtime,year
0,19000000.0,46998772.0,27998772.0,1.473620,927000.0,8.4,146.0,1980
1,4500000.0,58853106.0,54353106.0,12.078468,65000.0,5.8,104.0,1980
2,18000000.0,538375067.0,520375067.0,28.909726,1200000.0,8.7,124.0,1980
3,3500000.0,83453539.0,79953539.0,22.843868,221000.0,7.7,88.0,1980
4,6000000.0,39846344.0,33846344.0,5.641057,108000.0,7.3,98.0,1980

## Descriptive Statistics

In [22]:
numerical_data.describe().T

,count,mean,std,min,25%,50%,75%,max
budget,5497.0,3.558988e+07,4.145730e+07,3.000000e+03,1.000000e+07,2.050000e+07,4.500000e+07,3.560000e+08
gross,7479.0,7.850054e+07,1.657251e+08,3.090000e+02,4.532056e+06,2.020576e+07,7.601669e+07,2.847246e+09
Profit,5436.0,6.706582e+07,1.588181e+08,-1.580311e+08,-3.177509e+06,1.376612e+07,7.017584e+07,2.610246e+09
ROI,5436.0,5.719253e+00,1.838432e+02,-9.999794e-01,-2.767711e-01,8.328777e-01,2.671363e+00,1.288939e+04
votes,7665.0,8.810850e+04,1.633238e+05,7.000000e+00,9.100000e+03,3.300000e+04,9.300000e+04,2.400000e+06
score,7665.0,6.390411e+00,9.688416e-01,1.900000e+00,5.800000e+00,6.500000e+00,7.100000e+00,9.300000e+00
runtime,7664.0,1.072616e+02,1.858125e+01,5.500000e+01,9.500000e+01,1.040000e+02,1.160000e+02,3.660000e+02
year,7668.0,2.000405e+03,1.115351e+01,1.980000e+03,1.991000e+03,2.000000e+03,2.010000e+03,2.020000e+03

## Mean

In [23]:
mean = numerical_data.mean()
print(mean)

budget     3.558988e+07
gross      7.850054e+07
Profit     6.706582e+07
ROI        5.719253e+00
votes      8.810850e+04
score      6.390411e+00
runtime    1.072616e+02
year       2.000405e+03
dtype: float64

## Median

In [24]:
median = numerical_data.median()
print(median)

budget     2.050000e+07
gross      2.020576e+07
Profit     1.376612e+07
ROI        8.328777e-01
votes      3.300000e+04
score      6.500000e+00
runtime    1.040000e+02
year       2.000000e+03
dtype: float64

## Mode

In [25]:
mode = numerical_data.mode()
mode

,budget,gross,Profit,ROI,votes,score,runtime,year
0,20000000.0,14000000.0,-1.580311e+08,-0.2,13000.0,6.6,97.0,1985.0
1,NaN,NaN,-9.830110e+07,NaN,NaN,NaN,NaN,1986.0
2,NaN,NaN,-9.289603e+07,NaN,NaN,NaN,NaN,1987.0
3,NaN,NaN,-9.114436e+07,NaN,NaN,NaN,NaN,1988.0
4,NaN,NaN,-8.798268e+07,NaN,NaN,NaN,NaN,1989.0
...,...,...,...,...,...,...,...,...
5431,NaN,NaN,1.727360e+09,NaN,NaN,NaN,NaN,NaN
5432,NaN,NaN,1.824522e+09,NaN,NaN,NaN,NaN,NaN
5433,NaN,NaN,2.001647e+09,NaN,NaN,NaN,NaN,NaN
5434,NaN,NaN,2.441501e+09,NaN,NaN,NaN,NaN,NaN
5435,NaN,NaN,2.610246e+09,NaN,NaN,NaN,NaN,NaN

## Minimum and Maximum

In [26]:
summary = pd.DataFrame({
    'Minimum': numerical_data.min(),
    'Maximum': numerical_data.max()
})
summary

              Minimum       Maximum
budget   3.000000e+03  3.560000e+08
gross    3.090000e+02  2.847246e+09
Profit  -1.580311e+08  2.610246e+09
ROI     -9.999794e-01  1.288939e+04
votes    7.000000e+00  2.400000e+06
score    1.900000e+00  9.300000e+00
runtime  5.500000e+01  3.660000e+02
year     1.980000e+03  2.020000e+03

## Standard Deviation

In [27]:
std = numerical_data.std()
print(std)

budget     4.145730e+07
gross      1.657251e+08
Profit     1.588181e+08
ROI        1.838432e+02
votes      1.633238e+05
score      9.688416e-01
runtime    1.858125e+01
year       1.115351e+01
dtype: float64

## Quartiles

In [28]:
quartiles = numerical_data.quantile(
    [0.25, 0.5, 0.75]
)
quartiles

,budget,gross,Profit,ROI,votes,score,runtime,year
0.25,10000000.0,4532055.5,-3177509.0,-0.276771,9100.0,5.8,95.0,1991.0
0.50,20500000.0,20205757.0,13766118.0,0.832878,33000.0,6.5,104.0,2000.0
0.75,45000000.0,76016691.5,70175840.5,2.671363,93000.0,7.1,116.0,2010.0

## Interquartile Range

In [29]:
iqr = (
    numerical_data.quantile(0.75)
    -
    numerical_data.quantile(0.25)
)
print(iqr)

budget     3.500000e+07
gross      7.148464e+07
Profit     7.335335e+07
ROI        2.948134e+00
votes      8.390000e+04
score      1.300000e+00
runtime    2.100000e+01
year       1.900000e+01
dtype: float64

## Variance

In [30]:
variance = numerical_data.var()
print(variance)

budget     1.718707e+15
gross      2.746482e+16
Profit     2.522319e+16
ROI        3.379831e+04
votes      2.667465e+10
score      9.386541e-01
runtime    3.452628e+02
year       1.244007e+02
dtype: float64

## Skewness

In [31]:
skewness = numerical_data.skew()
print(skewness)

budget      2.453513
gross       5.314390
Profit      5.149280
ROI        65.449626
votes       4.907991
score      -0.604433
runtime     2.095743
year       -0.024649
dtype: float64

## Kurtosis

In [32]:
kurtosis = numerical_data.kurt()
print(kurtosis)

budget        7.500191
gross        45.506585
Profit       43.449340
ROI        4486.959304
votes        37.042069
score         0.892604
runtime      13.293461
year         -1.167559
dtype: float64