# Outlier Analysis
The objective of this notebook is to identify and investigate unusually high and low observations within the movie dataset that may influece statistical summaries and exploratory data analysis. By examining extreme values for production budgets, box office revenue, profitability, return on investment (ROI), audience votes, and IMDb ratings, this notebooks provides insight into blockbuster movies, financial failures, and exceptional performers that contribute to the highly skewed distributions identified in previous analyses.

## Research Questions:
- Is there a relationship between production budget and box office revenue?
- Does popularity influence commercial success?
- What qualities define blockbuster movies?
- Which movies achieved the highest financial efficiency (ROI)?

In [16]:
import pandas as pd

In [17]:
clean = (
    r"C:\Users\bongo\OneDrive\Desktop\GitHub"
    r"\Movie Analysis\Data\Clean\cleaned_movies.csv"
)

movies = pd.read_csv(clean)

print("Dataset loaded successfully.")

movies.head()

Dataset loaded successfully.

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
0,The Shining,R,Drama,1980,1980-06-13,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,1.473620,1980-06-13,2.0,1980
1,The Blue Lagoon,R,Adventure,1980,1980-07-02,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,12.078468,1980-07-02,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,1980-06-20,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,28.909726,1980-06-20,2.0,1980
3,Airplane!,PG,Comedy,1980,1980-07-02,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,22.843868,1980-07-02,3.0,1980
4,Caddyshack,R,Comedy,1980,1980-07-25,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,5.641057,1980-07-25,3.0,1980

In [18]:
print(f"Rows: {movies.shape[0]:,}")
print(f"Columns: {movies.shape[1]}")

movies.info()

Rows: 7,668
Columns: 20
<class 'pandas.DataFrame'>
RangeIndex: 7668 entries, 0 to 7667
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             7668 non-null   str
 1   rating           7591 non-null   str
 2   genre            7668 non-null   str
 3   year             7668 non-null   int64
 4   released         7609 non-null   str
 5   score            7665 non-null   float64
 6   votes            7665 non-null   float64
 7   director         7668 non-null   str
 8   writer           7665 non-null   str
 9   star             7667 non-null   str
 10  country          7665 non-null   str
 11  budget           5497 non-null   float64
 12  gross            7479 non-null   float64
 13  company          7651 non-null   str
 14  runtime          7664 non-null   float64
 15  Profit           5436 non-null   float64
 16  ROI              5436 non-null   float64
 17  released_month   7609 non-null   str
 18  release_quarter  7609 non-null   float64
 19  decade           7668 non-null   int64
dtypes: float64(8), int64(2), str(10)
memory usage: 1.2 MB

## Highest Production Budgets
Identify the most expensice movies ever produced within the dataset.

In [19]:
highest_budget = (
    movies[
        ['name', 'year', 'budget', 'gross', 'Profit', 'ROI']
    ]
    .sort_values(
        by='budget',
        ascending=False
    )
    .head(10)
)
highest_budget

,name,year,budget,gross,Profit,ROI
7445,Avengers: Endgame,2019,356000000.0,2.797501e+09,2.441501e+09,6.858150
7244,Avengers: Infinity War,2018,321000000.0,2.048360e+09,1.727360e+09,5.381183
7075,Star Wars: Episode VIII - The Last Jedi,2017,317000000.0,1.332699e+09,1.015699e+09,3.204097
7066,Justice League,2017,300000000.0,6.579270e+08,3.579270e+08,1.193090
5060,Pirates of the Caribbean: at World's End,2007,300000000.0,9.609965e+08,6.609965e+08,2.203322
7463,Star Wars: Episode IX - The Rise of Skywalker,2019,275000000.0,1.078233e+09,8.032326e+08,2.920846
7261,Solo: A Star Wars Story,2018,275000000.0,3.929248e+08,1.179248e+08,0.428817
4870,Superman Returns,2006,270000000.0,3.910812e+08,1.210812e+08,0.448449
5658,Tangled,2010,260000000.0,5.924628e+08,3.324628e+08,1.278703
7480,The Lion King,2019,260000000.0,1.670728e+09,1.410728e+09,5.425875

## Lowest Production Budgets
Identify movies produced with exceptionally small budgets.

In [20]:
lowest_budget = (
    movies[
        ['name', 'year', 'budget', 'gross', 'Profit', 'ROI']
    ]
    .sort_values(
        by='budget',
        ascending=True
    )
    .head(10)
)

lowest_budget

,name,year,budget,gross,Profit,ROI
471,A Polish Vampire in Burbank,1983,3000.0,NaN,NaN,NaN
7658,Black Wall Street Burning,2020,5000.0,NaN,NaN,NaN
3318,Following,1998,6000.0,48482.0,42482.0,7.080333
4507,Primer,2004,7000.0,545436.0,538436.0,76.919429
2093,El Mariachi,1992,7000.0,2040920.0,2033920.0,290.560000
7663,More to Life,2020,7000.0,NaN,NaN,NaN
7662,The Robinsons,2020,10000.0,NaN,NaN,NaN
327,Boardinghouse,1982,10000.0,NaN,NaN,NaN
5114,Paranormal Activity,2007,15000.0,193355800.0,193340800.0,12889.386667
7666,It's Just Us,2020,15000.0,NaN,NaN,NaN

## Highest Box Office Revenue
Identify the highest-grossing movies.

In [21]:
highest_revenue = (
    movies[
        ['name', 'year', 'budget', 'gross', 'Profit']
    ]
    .sort_values(
        by='gross',
        ascending=False
    )
    .head(10)
)

highest_revenue

,name,year,budget,gross,Profit
5445,Avatar,2009,237000000.0,2.847246e+09,2.610246e+09
7445,Avengers: Endgame,2019,356000000.0,2.797501e+09,2.441501e+09
3045,Titanic,1997,200000000.0,2.201647e+09,2.001647e+09
6663,Star Wars: Episode VII - The Force Awakens,2015,245000000.0,2.069522e+09,1.824522e+09
7244,Avengers: Infinity War,2018,321000000.0,2.048360e+09,1.727360e+09
7480,The Lion King,2019,260000000.0,1.670728e+09,1.410728e+09
6653,Jurassic World,2015,150000000.0,1.670516e+09,1.520516e+09
6043,The Avengers,2012,220000000.0,1.518816e+09,1.298816e+09
6646,Furious 7,2015,190000000.0,1.515341e+09,1.325341e+09
7494,Frozen II,2019,150000000.0,1.450027e+09,1.300027e+09

## Lowest Box Office Revenue
Identify the poorest performing movies financially.

In [22]:
lowest_revenue = (
    movies[
        ['name', 'year', 'gross', 'budget', 'Profit']
    ]
    .sort_values(
        by='gross',
        ascending=True
    )
    .head(10)
)

lowest_revenue

                      name  year   gross      budget      Profit
3203            Trojan War  1997   309.0  15000000.0 -14999691.0
2417              Madadayo  1993   596.0  11900000.0 -11899404.0
7580   Run with the Hunted  2019   682.0         NaN         NaN
7625      The Untold Story  2019   790.0         NaN         NaN
3818  Love, Honor and Obey  2000  1400.0         NaN         NaN
2906                Pusher  1996  1605.0         NaN         NaN
3394            I Want You  1998  1672.0         NaN         NaN
5524           Now & Later  2009  1808.0         NaN         NaN
6030          Angels Crest  2011  2037.0         NaN         NaN
272               Parasite  1982  2270.0    800000.0   -797730.0

## Highest ROI Movies
Identify the movies that generated the greatest financial return relative to their production budgets.

In [23]:
highest_roi = (
    movies[
        ['name', 'year', 'budget', 'gross', 'Profit', 'ROI']
    ]
    .sort_values(
        by='ROI',
        ascending=False
    )
    .head(10)
)

highest_roi

,name,year,budget,gross,Profit,ROI
5114,Paranormal Activity,2007,15000.0,193355800.0,193340800.0,12889.386667
3459,The Blair Witch Project,1999,60000.0,248639099.0,248579099.0,4142.984983
6815,The Gallows,2015,100000.0,42964410.0,42864410.0,428.644100
2093,El Mariachi,1992,7000.0,2040920.0,2033920.0,290.560000
5154,Once,2007,150000.0,20936722.0,20786722.0,138.578147
2467,Clerks,1994,27000.0,3151130.0,3124130.0,115.708519
4471,Napoleon Dynamite,2004,400000.0,46138887.0,45738887.0,114.347217
3233,In the Company of Men,1997,25000.0,2804473.0,2779473.0,111.178920
4814,Keeping Mum,2005,169000.0,18586834.0,18417834.0,108.981266
4304,Open Water,2003,500000.0,54683487.0,54183487.0,108.366974

## Lowest ROI Movies
Identify movies that produced the poorest financial returns.

In [24]:
lowest_roi = (
    movies[
        ['name', 'year', 'budget', 'gross', 'Profit', 'ROI']
    ]
    .sort_values(
        by='ROI',
        ascending=True
    )
    .head(10)
)

lowest_roi

,name,year,budget,gross,Profit,ROI
3203,Trojan War,1997,15000000.0,309.0,-14999691.0,-0.999979
2417,Madadayo,1993,11900000.0,596.0,-11899404.0,-0.999950
3681,Ginger Snaps,2000,5000000.0,2554.0,-4997446.0,-0.999489
2434,Philadelphia Experiment II,1993,5000000.0,2970.0,-4997030.0,-0.999406
1898,The Lovers on the Bridge,1991,28000000.0,29679.0,-27970321.0,-0.998940
3413,Savior,1998,10000000.0,14328.0,-9985672.0,-0.998567
5640,Tanner Hall,2009,3000000.0,5073.0,-2994927.0,-0.998309
760,Crimewave,1985,3000000.0,5101.0,-2994899.0,-0.998300
2401,Deadfall,1993,10000000.0,18369.0,-9981631.0,-0.998163
3438,Hell's Kitchen,1998,6000000.0,11710.0,-5988290.0,-0.998048

## Highest Audience Vote Counts
Identify movies with the greatest audience engagement

In [25]:
highest_votes = (
    movies[
        ['name', 'year', 'votes', 'score', 'gross']
    ]
    .sort_values(
        by='votes',
        ascending=False
    )
    .head(10)
)

highest_votes

,name,year,votes,score,gross
2443,The Shawshank Redemption,1994,2400000.0,9.3,2.881729e+07
5243,The Dark Knight,2008,2400000.0,9.0,1.005974e+09
5643,Inception,2010,2100000.0,8.8,8.368370e+08
3444,Fight Club,1999,1900000.0,8.8,1.012097e+08
2444,Pulp Fiction,1994,1900000.0,8.9,2.139288e+08
2445,Forrest Gump,1994,1900000.0,8.8,6.782261e+08
4245,The Lord of the Rings: The Return of the King,2003,1700000.0,8.9,1.146031e+09
3845,The Lord of the Rings: The Fellowship of the Ring,2001,1700000.0,8.8,8.976901e+08
3443,The Matrix,1999,1700000.0,8.7,4.663648e+08
6444,Interstellar,2014,1600000.0,8.6,7.017292e+08

## Highest IMDb Ratings
Identify the highest-rated in the dataset.

In [26]:
highest_scores = (
    movies[
        ['name', 'year', 'score', 'votes', 'gross']
    ]
    .sort_values(
        by=['score', 'votes'],
        ascending=[False, False]
    )
    .head(10)
)

highest_scores

,name,year,score,votes,gross
2443,The Shawshank Redemption,1994,9.3,2400000.0,2.881729e+07
5243,The Dark Knight,2008,9.0,2400000.0,1.005974e+09
2444,Pulp Fiction,1994,8.9,1900000.0,2.139288e+08
4245,The Lord of the Rings: The Return of the King,2003,8.9,1700000.0,1.146031e+09
2247,Schindler's List,1993,8.9,1200000.0,3.221612e+08
5643,Inception,2010,8.8,2100000.0,8.368370e+08
2445,Forrest Gump,1994,8.8,1900000.0,6.782261e+08
3444,Fight Club,1999,8.8,1900000.0,1.012097e+08
3845,The Lord of the Rings: The Fellowship of the Ring,2001,8.8,1700000.0,8.976901e+08
3443,The Matrix,1999,8.7,1700000.0,4.663648e+08