## SAVE THE CLEAN DATASET

This notebook defines the location where the cleaned dataset will be stored and exports the processed DataFrame for later use in SQLite and exploratory data analysis.

In [7]:
import os
import pandas as pd

In [8]:
# Path to the raw dataset
raw = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Data\Raw\movies.csv\movies.csv"

# Loading the dataset
movies = pd.read_csv(raw)

movies.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [9]:
# Profit
movies['Profit'] = movies['gross'] - movies['budget']

# Return on Investment (ROI)
movies['ROI'] = (
    movies['gross'] - movies['budget']
) / movies['budget']

# Removing country information from the release date
movies['released'] = movies['released'].str.replace(
    r"\s*\(.*\)",
    "",
    regex=True
)

# Convert to datetime
movies['released_month'] = pd.to_datetime(
    movies['released'],
    errors='coerce'
)

# Release Month
movies['released'] = pd.to_datetime(
    movies['released'],
    errors='coerce'
)
# Release Quarter
movies['release_quarter'] = movies['released'].dt.quarter

# Decade
movies['decade'] = (
    movies['year'] // 10
) * 10

In [10]:
clean = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Data\Clean"

clean_file = os.path.join(
    clean,
    "cleaned_movies.csv"
)

In [11]:
movies.to_csv(
    clean_file,
    index=False
)

print("Clean dataset saved successfully.")

print(f"\nLocation: \n{clean_file}")

Clean dataset saved successfully.

Location:
C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Data\Clean\cleaned_movies.csv

In [12]:
verification = pd.read_csv(clean_file)
verification.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
0,The Shining,R,Drama,1980,1980-06-13,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,1.473620,1980-06-13,2.0,1980
1,The Blue Lagoon,R,Adventure,1980,1980-07-02,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,12.078468,1980-07-02,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,1980-06-20,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,28.909726,1980-06-20,2.0,1980
3,Airplane!,PG,Comedy,1980,1980-07-02,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,22.843868,1980-07-02,3.0,1980
4,Caddyshack,R,Comedy,1980,1980-07-25,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,5.641057,1980-07-25,3.0,1980