In [1]:
import pandas as pd

In [3]:
raw = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Data\Raw\movies.csv\movies.csv"

movies = pd.read_csv(raw)

movies.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [4]:
movies['profit'] = movies['gross'] - movies['budget']
movies[['name', 'budget', 'gross', 'profit']].head()

,name,budget,gross,profit
0,The Shining,19000000.0,46998772.0,27998772.0
1,The Blue Lagoon,4500000.0,58853106.0,54353106.0
2,Star Wars: Episode V - The Empire Strikes Back,18000000.0,538375067.0,520375067.0
3,Airplane!,3500000.0,83453539.0,79953539.0
4,Caddyshack,6000000.0,39846344.0,33846344.0

In [7]:
movies['ROI'] = (
    movies['gross'] - movies['budget']
)/ movies['budget']

movies[['name','ROI']].head()

                                             name        ROI
0                                     The Shining   1.473620
1                                 The Blue Lagoon  12.078468
2  Star Wars: Episode V - The Empire Strikes Back  28.909726
3                                       Airplane!  22.843868
4                                      Caddyshack   5.641057

In [10]:
# Remove country information
movies['released'] = movies['released'].str.replace(
    r"\s*\(.*\)",
    "",
    regex=True
)

#Converting to datetime
movies['released'] = pd.to_datetime(
    movies['released'],
    errors = 'coerce'
)

movies[['released']].head()

    released
0 1980-06-13
1 1980-07-02
2 1980-06-20
3 1980-07-02
4 1980-07-25

In [13]:
movies['released_month'] = movies['released'].dt.month_name()
movies[['released', 'released_month']].head()

    released released_month
0 1980-06-13           June
1 1980-07-02           July
2 1980-06-20           June
3 1980-07-02           July
4 1980-07-25           July

In [17]:
movies['release_quarter'] = movies['released'].dt.quarter
movies[['released', 'release_quarter']].head()

    released  release_quarter
0 1980-06-13              2.0
1 1980-07-02              3.0
2 1980-06-20              2.0
3 1980-07-02              3.0
4 1980-07-25              3.0

In [18]:
movies['decade'] = (
    movies['year']//10
)*10
movies[['year', 'decade']].head()

   year  decade
0  1980    1980
1  1980    1980
2  1980    1980
3  1980    1980
4  1980    1980

In [20]:
movies[[
    'name',
    'budget',
    'gross',
    'profit',
    'ROI',
    'released_month',
    'release_quarter',
    'decade'
]].head(10)

,name,budget,gross,profit,ROI,released_month,release_quarter,decade
0,The Shining,19000000.0,46998772.0,27998772.0,1.473620,June,2.0,1980
1,The Blue Lagoon,4500000.0,58853106.0,54353106.0,12.078468,July,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,18000000.0,538375067.0,520375067.0,28.909726,June,2.0,1980
3,Airplane!,3500000.0,83453539.0,79953539.0,22.843868,July,3.0,1980
4,Caddyshack,6000000.0,39846344.0,33846344.0,5.641057,July,3.0,1980
5,Friday the 13th,550000.0,39754601.0,39204601.0,71.281093,May,2.0,1980
6,The Blues Brothers,27000000.0,115229890.0,88229890.0,3.267774,June,2.0,1980
7,Raging Bull,18000000.0,23402427.0,5402427.0,0.300135,December,4.0,1980
8,Superman II,54000000.0,108185706.0,54185706.0,1.003439,June,2.0,1980
9,The Long Riders,10000000.0,15795189.0,5795189.0,0.579519,May,2.0,1980