## INITIAL DATA EXPLORATION

The purpose of this notebook is to explore the cleaned movie dataset after feature engineering has been completed.
This notebook evaluated the overall quality of the dataset by examining its structute, dimensions, data types, descriptive statistics, missing values, duplicate records, and overall completeness before loading the data into SQLite.

In [1]:
import pandas as pd

In [6]:
# Path to the clean dataset
clean = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Data\Clean\cleaned_movies.csv"

# Loading the dataset
movies = pd.read_csv(clean)

In [7]:
movies.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
0,The Shining,R,Drama,1980,1980-06-13,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,1.473620,1980-06-13,2.0,1980
1,The Blue Lagoon,R,Adventure,1980,1980-07-02,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,12.078468,1980-07-02,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,1980-06-20,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,28.909726,1980-06-20,2.0,1980
3,Airplane!,PG,Comedy,1980,1980-07-02,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,22.843868,1980-07-02,3.0,1980
4,Caddyshack,R,Comedy,1980,1980-07-25,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,5.641057,1980-07-25,3.0,1980

In [8]:
movies.tail()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
7663,More to Life,NaN,Drama,2020,2020-10-23,3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0,NaN,NaN,2020-10-23,4.0,2020
7664,Dream Round,NaN,Comedy,2020,2020-02-07,4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0,NaN,NaN,2020-02-07,1.0,2020
7665,Saving Mbango,NaN,Drama,2020,2020-04-27,5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN,NaN,NaN,2020-04-27,2.0,2020
7666,It's Just Us,NaN,Drama,2020,2020-10-01,NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0,NaN,NaN,2020-10-01,4.0,2020
7667,Tee em el,NaN,Horror,2020,2020-08-19,5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0,NaN,NaN,2020-08-19,3.0,2020

In [9]:
print(f"Rows: {movies.shape[0]:,}")
print(f"Columns: {movies.shape[1]:,}")

Rows: 7,668
Columns: 20

In [10]:
movies.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime', 'Profit', 'ROI', 'released_month', 'release_quarter',
       'decade'],
      dtype='str')

In [11]:
movies.dtypes

name                   str
rating                 str
genre                  str
year                 int64
released               str
score              float64
votes              float64
director               str
writer                 str
star                   str
country                str
budget             float64
gross              float64
company                str
runtime            float64
Profit             float64
ROI                float64
released_month         str
release_quarter    float64
decade               int64
dtype: object

In [12]:
movies.describe(include="all")

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
count,7668,7591,7668,7668.000000,7609,7665.000000,7.665000e+03,7668,7665,7667,7665,5.497000e+03,7.479000e+03,7651,7664.000000,5.436000e+03,5436.000000,7609,7609.000000,7668.000000
unique,7512,12,19,NaN,2909,NaN,NaN,2949,4535,2814,59,NaN,NaN,2385,NaN,NaN,NaN,2909,NaN,NaN
top,Venom,R,Comedy,NaN,1986-02-14,NaN,NaN,Woody Allen,Woody Allen,Nicolas Cage,United States,NaN,NaN,Universal Pictures,NaN,NaN,NaN,1986-02-14,NaN,NaN
freq,3,3697,2245,NaN,9,NaN,NaN,38,37,43,5475,NaN,NaN,377,NaN,NaN,NaN,9,NaN,NaN
mean,NaN,NaN,NaN,2000.405451,NaN,6.390411,8.810850e+04,NaN,NaN,NaN,NaN,3.558988e+07,7.850054e+07,NaN,107.261613,6.706582e+07,5.719253,NaN,2.532527,1995.779864
std,NaN,NaN,NaN,11.153508,NaN,0.968842,1.633238e+05,NaN,NaN,NaN,NaN,4.145730e+07,1.657251e+08,NaN,18.581247,1.588181e+08,183.843156,NaN,1.125428,11.017354
min,NaN,NaN,NaN,1980.000000,NaN,1.900000,7.000000e+00,NaN,NaN,NaN,NaN,3.000000e+03,3.090000e+02,NaN,55.000000,-1.580311e+08,-0.999979,NaN,1.000000,1980.000000
25%,NaN,NaN,NaN,1991.000000,NaN,5.800000,9.100000e+03,NaN,NaN,NaN,NaN,1.000000e+07,4.532056e+06,NaN,95.000000,-3.177509e+06,-0.276771,NaN,2.000000,1990.000000
50%,NaN,NaN,NaN,2000.000000,NaN,6.500000,3.300000e+04,NaN,NaN,NaN,NaN,2.050000e+07,2.020576e+07,NaN,104.000000,1.376612e+07,0.832878,NaN,3.000000,2000.000000
75%,NaN,NaN,NaN,2010.000000,NaN,7.100000,9.300000e+04,NaN,NaN,NaN,NaN,4.500000e+07,7.601669e+07,NaN,116.000000,7.017584e+07,2.671363,NaN,4.000000,2010.000000
max,NaN,NaN,NaN,2020.000000,NaN,9.300000,2.400000e+06,NaN,NaN,NaN,NaN,3.560000e+08,2.847246e+09,NaN,366.000000,2.610246e+09,12889.386667,NaN,4.000000,2020.000000

In [13]:
movies.isnull().sum()

name                  0
rating               77
genre                 0
year                  0
released             59
score                 3
votes                 3
director              0
writer                3
star                  1
country               3
budget             2171
gross               189
company              17
runtime               4
Profit             2232
ROI                2232
released_month       59
release_quarter      59
decade                0
dtype: int64

In [14]:
duplicates = movies.duplicated().sum()
print(f"Duplicate Records: {duplicates}")

Duplicate Records: 0

In [15]:
if duplicates > 0:
    movies[movies.duplicated()]
else:
    print('No duplicate records found')

No duplicate records found

### INITIAL DATA QUALITY REPORT

A summary report is produced to provide an overview of the dataset's overall quality.
This report consolidates key quality metrics into a single table for easy interpretation.

In [16]:
quality_report = pd.DataFrame({
    
    'Metric': [
        'Rows',
        'Columns',
        'Missing Values',
        'Duplicate Records'
    ],

    'Value': [
        movies.shape[0],
        movies.shape[1],
        movies.isna().sum().sum(),
        duplicates
    ]
})

quality_report

              Metric  Value
0               Rows   7668
1            Columns     20
2     Missing Values   7112
3  Duplicate Records      0