## Loading clean dataset into SQLite

## SQLite Database Connection

The purpose of this notebook is to create a SQLite database and load the cleaned movie dataset into a relationship database management system (RDBMS).
After loading the data, several validation checks are performed to cerify that the dataset has been successfully imported. These include checking the number of rows and columns, inspecting the database schema, and executing sample SQL queries.
The SQLite database will serve as the foundation for the SQL analysis phase of this project.

In [3]:
import sqlite3
import os
import pandas as pd

In [4]:
DATABASE_FOLDER = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database"

os.makedirs(
    DATABASE_FOLDER,
    exist_ok=True
)

In [5]:
database_path  = os.path.join(
    DATABASE_FOLDER,
    'movie_industry.db'
)
connection = sqlite3.connect(database_path)
print("SQLite database created successfully.")
print(database_path)
print('SQLite database created successfully.')

print(database_path)

SQLite database created successfully.
C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db
SQLite database created successfully.
C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db

In [6]:
clean = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Data\Clean\cleaned_movies.csv"

movies = pd.read_csv(clean)
movies.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
0,The Shining,R,Drama,1980,1980-06-13,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,1.473620,1980-06-13,2.0,1980
1,The Blue Lagoon,R,Adventure,1980,1980-07-02,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,12.078468,1980-07-02,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,1980-06-20,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,28.909726,1980-06-20,2.0,1980
3,Airplane!,PG,Comedy,1980,1980-07-02,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,22.843868,1980-07-02,3.0,1980
4,Caddyshack,R,Comedy,1980,1980-07-25,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,5.641057,1980-07-25,3.0,1980

In [8]:
movies.to_sql(
    name = 'movies',
    con = connection,
    if_exists = 'replace',
    index = False
)
print("Dataset loaded successfully")

Dataset loaded successfully

In [10]:
cursor = connection.cursor()
cursor.execute("""
                SELECT COUNT(*)
                FROM movies;
                """)
row_count = cursor.fetchone()[0]
print(f"Rows loaded into SQLite: {row_count:,}")

Rows loaded into SQLite: 7,668

In [11]:
cursor.execute("""
               PRAGMA table_info(movies);
               
               """)
columns = cursor.fetchall()
print(f"Number of Columns: {len(columns)}")
columns

Number of Columns: 20

[(0, 'name', 'TEXT', 0, None, 0),
 (1, 'rating', 'TEXT', 0, None, 0),
 (2, 'genre', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'released', 'TEXT', 0, None, 0),
 (5, 'score', 'REAL', 0, None, 0),
 (6, 'votes', 'REAL', 0, None, 0),
 (7, 'director', 'TEXT', 0, None, 0),
 (8, 'writer', 'TEXT', 0, None, 0),
 (9, 'star', 'TEXT', 0, None, 0),
 (10, 'country', 'TEXT', 0, None, 0),
 (11, 'budget', 'REAL', 0, None, 0),
 (12, 'gross', 'REAL', 0, None, 0),
 (13, 'company', 'TEXT', 0, None, 0),
 (14, 'runtime', 'REAL', 0, None, 0),
 (15, 'Profit', 'REAL', 0, None, 0),
 (16, 'ROI', 'REAL', 0, None, 0),
 (17, 'released_month', 'TEXT', 0, None, 0),
 (18, 'release_quarter', 'REAL', 0, None, 0),
 (19, 'decade', 'INTEGER', 0, None, 0)]

In [12]:
for column in columns:
    print(column[1])

name
rating
genre
year
released
score
votes
director
writer
star
country
budget
gross
company
runtime
Profit
ROI
released_month
release_quarter
decade

## Execute Test Query 1

The first five records are retrieved directly from SQLite.
This confirms that the data can be queried successfully after being loaded into the database.

In [13]:
query = """
SELECT *
FROM movies
LIMIT 5;
"""

pd.read_sql(query, connection)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Profit,ROI,released_month,release_quarter,decade
0,The Shining,R,Drama,1980,1980-06-13,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,1.473620,1980-06-13,2.0,1980
1,The Blue Lagoon,R,Adventure,1980,1980-07-02,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,12.078468,1980-07-02,3.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,1980-06-20,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,28.909726,1980-06-20,2.0,1980
3,Airplane!,PG,Comedy,1980,1980-07-02,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,22.843868,1980-07-02,3.0,1980
4,Caddyshack,R,Comedy,1980,1980-07-25,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,5.641057,1980-07-25,3.0,1980

## Execute Test Query 2
Basic summary statistics are calculated using SQL.
This verifies that aggregate SQL functions operate correctly on the imported dataset.

In [14]:
query = """
SELECT
    COUNT(*) AS TotalMovies,
    AVG(gross) AS AverageRevenue,
    MAX(gross) AS HighestRevenue
FROM movies;

"""

In [15]:
connection.close()
print('Database connection closed.')

Database connection closed.